name: CI Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'
      - name: "Version"
        run: go version
      - name: "Build"
        run: go build
      - name: "Test"
        run: go test
